### ISSUE TITLE
about"mobilevit"

### ISSUE THREAD

**Issue by JGGGBang** [fisherliaoc/SfMLearner-WCE#1]
I would like to ask a question about   "from mobilevit import * "   in terms of mobilevit. 
What is the bottleneck in " bottleneck, x3, x2, x1=self. vit (tl, r_i) "? I would like to know the specific code of Mobilevit

**Comment by fisherliaoc** [comment]
> I would like to ask a question about "from mobilevit import * " in terms of mobilevit. What is the bottleneck in " bottleneck, x3, x2, x1=self. vit (tl, r_i) "? I would like to know the specific code of Mobilevit

Sorry for the late reply; I will upload mobilevit.py later today.

**Comment by fisherliaoc** [comment]
> I would like to ask a question about "from mobilevit import * " in terms of mobilevit. What is the bottleneck in " bottleneck, x3, x2, x1=self. vit (tl, r_i) "? I would like to know the specific code of Mobilevit

Sorry for the late reply; I will upload mobilevit.py later today.

**Comment by JGGGBang** [comment]
Thank you very much
